# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Runs a single command using the runners shell
      - name: Run build for hello-test
        env:
          IMAGE_TAG: 0.0.3-SNAPSHOT
          DOCKER_REPOSITORY: ravr
          ARTIFACT: ms2-hellotextkubernetes
        run: |
          cd hellotextkubernetes
          echo "./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=$DOCKER_REPOSITORY/$ARTIFACT:$IMAGE_TAG"
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=$DOCKER_REPOSITORY/$ARTIFACT:$IMAGE_TAG
          echo "docker tag $DOCKER_REPOSITORY $DOCKER_REPOSITORY/$ARTIFACT:$IMAGE_TAG"
          docker tag $DOCKER_REPOSITORY $DOCKER_REPOSITORY/$ARTIFACT:$IMAGE_TAG
          echo "docker push $DOCKER_REPOSITORY/$ARTIFACT:$IMAGE_TAG"
          docker push $DOCKER_REPOSITORY/$ARTIFACT:$IMAGE_TAG